///////////////////////////////////////////////////////////////////////////////
// MyFirstTrafoServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MyFirstTrafo = 0x3F000000;
#define SRVNAME_MYFIRSTTRAFO "MyFirstTrafo"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MyFirstTrafoCMyFirstTrafo = {0xc0dc526c,0xf26b,0x4b3e,{0xb0,0x08,0xd3,0xcf,0xac,0x3b,0x0a,0x7b}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MyFirstTrafoZHeight = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("05010001-0000-0000-e000-000000000064", ITcNcTrafo)
#endif // !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
